# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end

  config.vm.define :clienteUbuntu do |clienteUbuntu|
    clienteUbuntu.vm.box = "ubuntu/bionic64"
    clienteUbuntu.vm.network :private_network, ip: "192.168.100.20"
    clienteUbuntu.vm.hostname = "clienteUbuntu"
  end

  config.vm.define :servidorUbuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "ubuntu/bionic64"
    servidorUbuntu.vm.network :private_network, ip: "192.168.100.30"
    servidorUbuntu.vm.hostname = "servidorUbuntu"
  end
end